version: '3.4'

name: nodeguard
services:
  nodeguard_postgres:
    container_name: nodeguard_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nodeguard
      POSTGRES_USER: rw_dev
      POSTGRES_PASSWORD: rw_dev
      TZ: Europe/Madrid
    volumes:
      - nodeguard_postgres_data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  nbxplorer:
    restart: unless-stopped
    image: ghcr.io/elenpay/nbxplorer:elenpay-develop
    platform: linux/amd64
    hostname: nbxplorer
    ports:
      - "32838:32838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      #Keeping dbtrie for dev until it is fully removed since we would need to modify nbxplorer docker image to wait for the db to be ready
      NBXPLORER_DBTRIE: 0
      NBXPLORER_POSTGRES: Host=nbxplorer_postgres;Port=5432;Database=nbxplorer;Username=rw_dev;Password=rw_dev
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCUSER: "polaruser"
      NBXPLORER_BTCRPCPASSWORD: "polarpass"
      NBXPLORER_BTCRPCURL: http://host.docker.internal:18443/
      NBXPLORER_BTCNODEENDPOINT: host.docker.internal:19444
    command: ["--noauth"]
    volumes:
      - "bitcoin_datadir:/root/.bitcoin"
  
  nbxplorer_postgres:
    container_name: nbxplorer_postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: nbxplorer
      POSTGRES_USER: rw_dev
      POSTGRES_PASSWORD: rw_dev
      TZ: Europe/Madrid
    volumes:
      - nbxplorer_postgres_data:/var/lib/postgresql/data
    ports:
      - 35432:5432



volumes:
  nodeguard_postgres_data:
  bitcoin_datadir:
  nbxplorer_datadir:
  nbxplorer_postgres_data:
  nodeguard_data_keys_dir:
