version: '3.4'

services:
  fundsmanager_postgres:
    container_name: fundsmanager_postgres
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_DB: fundsmanager
      POSTGRES_USER: rw_dev
      POSTGRES_PASSWORD: rw_dev
      TZ: Europe/Madrid
    volumes:
      - fundsmanager_postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.3.40
    hostname: nbxplorer
    ports:
    - "32838:32838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      #Keeping dbtrie for dev until it is fully removed since we would need to modify nbxplorer docker image to wait for the db to be ready
      NBXPLORER_DBTRIE: 1
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCUSER: "polaruser"
      NBXPLORER_BTCRPCPASSWORD: "polarpass"
      NBXPLORER_BTCRPCURL: http://backend1:18443/
      NBXPLORER_BTCNODEENDPOINT: backend1:18444
    command: ["--noauth"]
    volumes:
    - "bitcoin_datadir:/root/.bitcoin"

  backend1:
    image: polarlightning/bitcoind:23.0
    container_name: polar-n1-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0
      -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1
      -listenonion=0 -fallbackfee=0.0002 -whitelist=0.0.0.0/0
    volumes:
      - ./volumes/bitcoind/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  alice:
    image: polarlightning/lnd:0.15.0-beta
    container_name: polar-n1-alice
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: alice
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=alice --externalip=alice
      --tlsextradomain=alice --tlsextradomain=polar-n1-alice
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/alice:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8081:8080'
      - '10001:10009'
      - '9735:9735'
  bob:
    image: polarlightning/eclair:0.6.0
    container_name: polar-n1-bob
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bob
    command: >-
      polar-eclair --node-alias=bob --server.public-ips.0=bob --server.port=9735
      --api.enabled=true --api.binding-ip=0.0.0.0 --api.port=8080
      --api.password=eclairpw --chain=regtest --bitcoind.host=polar-n1-backend1
      --bitcoind.rpcport=18443 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpassword=polarpass
      --bitcoind.zmqblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqtx=tcp://polar-n1-backend1:28335
      --datadir=/home/eclair/.eclair --printToConsole=true
      --on-chain-fees.feerate-tolerance.ratio-low=0.00001
      --on-chain-fees.feerate-tolerance.ratio-high=10000.0
    restart: always
    volumes:
      - ./volumes/eclair/bob:/home/eclair/.eclair
    expose:
      - '8080'
      - '9735'
    ports:
      - '8282:8080'
      - '9936:9735'
  carol:
    image: polarlightning/lnd:0.15.0-beta
    container_name: polar-n1-carol
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: carol
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=carol --externalip=carol
      --tlsextradomain=carol --tlsextradomain=polar-n1-carol
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-backend1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-backend1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-backend1:28335
    restart: always
    volumes:
      - ./volumes/lnd/carol:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10003:10009'
      - '9737:9735'

  redis:
    hostname: redis
    image: redis:7-bullseye
    restart: always
    command: redis-server --save 60 1 --bind 0.0.0.0
    volumes:
        - redis_data:/data      

volumes:
    fundsmanager_postgres_data:
    bitcoin_datadir: 
    nbxplorer_datadir: 
    fundsmanager_data_keys_dir:
    redis_data:
