- name: Deploy staging
  vars:
    ASPNETCORE_ENVIRONMENT: Development
    BITCOIN_NETWORK: REGTEST
    CI_BUILD_TOKEN: "{{ lookup('env','CI_BUILD_TOKEN') }}"
    DEFAULT_DERIVATION_PATH: m/48'/1'/1'
    FUNDSMANAGER_ENDPOINT: https://fm-staging.elenpay.tech
    FUNDSMANAGER_IMAGE_TAG: develop
    POSTGRES_CONNECTIONSTRING: Host=fundsmanager_postgres;Port=5432;Database=fundsmanager;Username=rw_dev;Password=rw_dev
    MAX_BTC: "{{ lookup('env','MAX_BTC') }}"
    MEMPOOL_ENDPOINT: "https://mempool-staging.elenpay.tech"
    NBXPLORER_BTCNODEENDPOINT: 10.8.0.10:18444
    NBXPLORER_BTCRPCPASSWORD: "{{ lookup('env','BITCOIND_PASSWORD_STAGING') }}"
    NBXPLORER_BTCRPCURL: http://10.8.0.10:18443/
    NBXPLORER_BTCRPCUSER: "{{ lookup('env','BITCOIND_RPCUSER_STAGING') }}"
    NBXPLORER_URI: http://172.17.0.1:32838
    SENTRY_DSN: https://6e10418190404837853e31beaefb94c4@o1066831.ingest.sentry.io/6599373
    SENTRY_ENVIRONMENT: PASSED_BY_CLI
    SWEEPNODEWALLETSJOB_CRON: "0 */1 * * * ?" # Every Minute
    ANCHOR_CLOSINGS_MINIMUM_SATS: 100000 # Check https://github.com/lightningnetwork/lnd/issues/6505#issuecomment-1120364460 to understand, we need 100K to support anchor channel closings
    AWS_ACCESS_KEY_ID: PASSED_BY_CLI
    AWS_SECRET_ACCESS_KEY: PASSED_BY_CLI
    AWS_REGION: "{{ lookup('env','AWS_REGION') }}"
    AWS_KMS_KEY_ID: PASSED_BY_CLI
    FM_SIGNER_ENDPOINT: PASSED_BY_CLI
    MINIMUM_WITHDRAWAL_BTC_AMOUNT: 0.001
    MINIMUM_CHANNEL_CAPACITY_SATS: 20000
    TRANSACTION_CONFIRMATION_MINIMUM_BLOCKS: 6
    MONITOR_WITHDRAWALS_CRON: "0 */1 * * * ?" # Every Minute
    COINGECKO_ENDPOINT: "{{ lookup('env','COINGECKO_ENDPOINT') }}"
    COINGECKO_KEY: "{{ lookup('env','COINGECKO_KEY') }}"
  hosts: 
   - btcpay-staging
  tasks:
    - name: Upload compose
      ansible.builtin.template:
        src: docker-compose.deploy.yaml
        dest: /home/ubuntu/fundsmanager/docker-compose.yaml
        mode: "0644"
      diff: yes
    - name: Docker login
      shell: sudo docker login -u gitlab-ci-token -p {{ CI_BUILD_TOKEN }} registry.gitlab.com
    - name: Pull image
      ansible.builtin.shell:
        cmd: sudo docker-compose pull
        chdir: /home/ubuntu/fundsmanager
    - name: Deploy changes
      ansible.builtin.shell:
        cmd: sudo docker-compose up -d
        chdir: /home/ubuntu/fundsmanager      
