version: '3.4'

services:
  fundsmanager:
    container_name: fundsmanager
    hostname: fundsmanager
    restart: always
    image: registry.gitlab.com/clovrlabs/lightningnetwork/fundsmanager:{{ FUNDSMANAGER_IMAGE_TAG }}
    pull_policy: always
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "{{ ASPNETCORE_ENVIRONMENT }}"
      BITCOIN_NETWORK: "{{ BITCOIN_NETWORK }}"
      DEFAULT_DERIVATION_PATH: "{{ DEFAULT_DERIVATION_PATH }}"
      FUNDSMANAGER_ENDPOINT: "{{ FUNDSMANAGER_ENDPOINT }}"
      Logging__LogLevel__Microsoft: Warning
      MEMPOOL_ENDPOINT: "{{ MEMPOOL_ENDPOINT }}"
      NBXPLORER_BTCNODEENDPOINT: "{{ NBXPLORER_BTCNODEENDPOINT }}"
      NBXPLORER_BTCRPCPASSWORD: "{{ NBXPLORER_BTCRPCPASSWORD }}"
      NBXPLORER_BTCRPCURL: "{{ NBXPLORER_BTCRPCURL }}"
      NBXPLORER_BTCRPCUSER: "{{ NBXPLORER_BTCRPCUSER }}"
      NBXPLORER_URI: "{{ NBXPLORER_URI }}"
      POSTGRES_CONNECTIONSTRING: "{{ POSTGRES_CONNECTIONSTRING }}"
      SENTRY_DSN:  "{{ SENTRY_DSN }}"
      SENTRY_ENVIRONMENT: "{{ SENTRY_ENVIRONMENT }}"
      SWEEPNODEWALLETSJOB_CRON: "{{ SWEEPNODEWALLETSJOB_CRON }}"
      ENABLE_HW_SUPPORT: "false" # Enables fields and features for using Hardware Wallets

    volumes:
      - fundsmanager_data_keys_dir:/root/.aspnet/DataProtection-Keys

  fundsmanager_postgres:
    container_name: fundsmanager_postgres
    hostname: fundsmanager_postgres
    pull_policy: always
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fundsmanager
      POSTGRES_USER: rw_dev
      POSTGRES_PASSWORD: rw_dev
      TZ: Europe/Madrid
    volumes:
      - fundsmanager_postgres_data:/var/lib/postgresql/data

volumes:
  fundsmanager_postgres_data:
  fundsmanager_data_keys_dir:
