name: Docker image build
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/Dockerfile
          push: true
          sbom: true
          platforms: linux/amd64,linux/arm64
          provenance: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan SBOM
        uses: anchore/scan-action@v3
        with:
          image: ${{ steps.meta.outputs.tags }}
          add-cpes-if-none: true
          output-format: table
          severity-cutoff: critical
          # fail-build: true
          fail-build: false