name: Unit testing

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
    - name: ls
      run: ls -la /home/runner/work/NodeGuard/NodeGuard

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test
