name: polar

x-lnd-node: &lnd-node
  profiles: [polar]
  image: lightninglabs/lndinit:v0.1.28-beta-lnd-v0.19.0-beta
  environment:
    USERID: ${USERID:-1000}
    GROUPID: ${GROUPID:-1000}
  depends_on:
    - bitcoind
  healthcheck:
    test: "lncli -n regtest getinfo"
    interval: 1s
    retries: 30

services:
  bitcoind:
    profiles: [polar]
    container_name: polar-n1-backend
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 5m
    image: polarlightning/bitcoind:${BITCOIND_VERSION:-29.0}
    command: >-
      bitcoind -server=1 -regtest=1 -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526 -zmqpubrawblock=tcp://0.0.0.0:28334 -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336 -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002 -whitelist=0.0.0.0/0
    ports:
      - 18443:18443

  alice:
    <<: *lnd-node
    container_name: polar-n1-alice
    entrypoint: /init/lnd-entrypoint.sh alice
    volumes:
      - ./init:/init
      - alice_lnd_data:/root/.lnd
      - shared_data:/shared
    depends_on:
      - bitcoind
    ports:
      - 10001:10009

  bob:
    <<: *lnd-node
    container_name: polar-n1-bob
    entrypoint: /init/lnd-entrypoint.sh bob
    volumes:
      - ./init:/init
      - bob_lnd_data:/root/.lnd
    ports:
      - 10002:10009

  carol:
    <<: *lnd-node
    container_name: polar-n1-carol
    entrypoint: /init/lnd-entrypoint.sh carol
    volumes:
      - ./init:/init
      - carol_lnd_data:/root/.lnd
    ports:
      - 10003:10009

  setup:
    profiles: [polar]
    image: alpine:latest
    container_name: polar-n1-setup
    depends_on:
      bitcoind:
        condition: service_started
      alice:
        condition: service_healthy
      bob:
        condition: service_healthy
      carol:
        condition: service_healthy
    volumes:
      - ./:/docker
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "apk add --no-cache docker-cli jq && /docker/setup.sh"
    restart: "no"

volumes:
  alice_datadir:
  bob_datadir:
  carol_datadir:
  alice_lnd_data:
  bob_lnd_data:
  carol_lnd_data:
  shared_data: